language: python
python:
  - '2.7'

#we want a newer cppcheck, so use trusty
dist: bionic

sudo: false

cache:
  directories:
  # - "~/.platformio"
  # - "./.pio"



addons:
  apt:
    packages:
    - cppcheck
    - binutils


install:
  - pip install -U platformio sphinx recommonmark sphinx_bootstrap_theme

script:
  - platformio update
  # patch platformio core libs for PUYA bug (https://github.com/letscontrolit/ESPEasy/issues/650)
  - cd patches; ./check_puya_patch; cd ..

  # - bash ./preflight.sh # make sure input files are OK before wasting time with prereqs
  # - cppcheck --enable=warning src/*.ino -q --force -I src --include=src/ESPEasy.ino --error-exitcode=1
  # - ./memanalyzer.py ~/.platformio/packages/toolchain-xtensa/bin/xtensa-lx106-elf-objdump
  # - PLATFORMIO_BUILD_FLAGS="-D CONTINUOUS_INTEGRATION" platformio run --target clean
  # Same list as in tools/build_ESPeasy.sh  and before_deploy
  - PLATFORMIO_BUILD_FLAGS="-D CONTINUOUS_INTEGRATION" platformio run -e dev_ESP8266_4M1M
  - PLATFORMIO_BUILD_FLAGS="-D CONTINUOUS_INTEGRATION" platformio run -e test_ESP32_4M316k

before_deploy:
  - ./before_deploy
  - export RELEASE_FILE=$(ls ESPEasy*.zip)

notifications:
  email: false
